# Taller Integrador

In [7]:
import pandas as pd
#print(pd.__version__)
df = pd.read_csv("estudiantes.csv")
df

    id            nombre  edad        ciudad  cursos_previos  promedio  activo
0    1       Laura Gómez    42      Medellín               0       8.3    True
1    2      Carlos Pérez    29          Cali               1       7.9    True
2    3        Anita Ruiz    40       Pereira               0       3.7    True
3    4       Juan Torres    29        Bogotá               8       4.8   False
4    5       María López    29     Manizales               4       8.8    True
5    6     Andrés Castro    27       Pereira               5       5.3    True
6    7     Sofía Herrera    32      Medellín               1       6.0    True
7    8    Diego Martínez    33     Cartagena               0       8.2    True
8    9    Valentina Ríos    34      Medellín               8       5.4    True
9   10       Felipe Mora    40  Barranquilla               1       3.8    True
10  11     Camila Vargas    31      Medellín               3       9.1   False
11  12    Sebastián Díaz    30     Manizales               5       4.6    True
12  13  Isabella Ramírez    28     Cartagena               1       7.5    True
13  14      Mateo Suárez    39  Barranquilla               2       6.5    True
14  15   Lucía Fernández    42  Barranquilla               5       9.0    True
15  16     Daniel Ortega    29        Bogotá               5       6.1    True
16  17  Gabriela Mendoza    28   Bucaramanga               3       7.8   False
17  18  Alejandro Flores    42     Manizales               2       5.2    True
18  19     Natalia Reyes    45     Cartagena               6       9.3   False
19  20     Ricardo Rojas    33  Barranquilla               2       6.8    True

Pandas -> Libreria python
DataFrame -> estructura que crea panda cuando carga un csv. Tiene por lo general filas y columnas

In [12]:
#shape devuelve el valor de (Filas y Columnas)
print(df.shape)


#columns.tolist devuelve nombres exactos de columnas 
print(df.columns.tolist())

(20, 7)
['id', 'nombre', 'edad', 'ciudad', 'cursos_previos', 'promedio', 'activo']

In [30]:
#muestra la columna completa con todas sus filas 
df["nombre"]

0          Laura Gómez
1         Carlos Pérez
2           Anita Ruiz
3          Juan Torres
4          María López
5        Andrés Castro
6        Sofía Herrera
7       Diego Martínez
8       Valentina Ríos
9          Felipe Mora
10       Camila Vargas
11      Sebastián Díaz
12    Isabella Ramírez
13        Mateo Suárez
14     Lucía Fernández
15       Daniel Ortega
16    Gabriela Mendoza
17    Alejandro Flores
18       Natalia Reyes
19       Ricardo Rojas
Name: nombre, dtype: str

In [ ]:
#.loc[] te permite llegar a una informacion por medio de indice
print(df.loc[0, "nombre"])
print(df.loc[3, "promedio"])

Laura Gómez
4.8

In [22]:
#me permite orientarme con respecto a la data que estoy trabajando
df.head(10)

   id          nombre  edad        ciudad  cursos_previos  promedio  activo
0   1     Laura Gómez    42      Medellín               0       8.3    True
1   2    Carlos Pérez    29          Cali               1       7.9    True
2   3      Anita Ruiz    40       Pereira               0       3.7    True
3   4     Juan Torres    29        Bogotá               8       4.8   False
4   5     María López    29     Manizales               4       8.8    True
5   6   Andrés Castro    27       Pereira               5       5.3    True
6   7   Sofía Herrera    32      Medellín               1       6.0    True
7   8  Diego Martínez    33     Cartagena               0       8.2    True
8   9  Valentina Ríos    34      Medellín               8       5.4    True
9  10     Felipe Mora    40  Barranquilla               1       3.8    True

In [20]:
df.describe()

             id       edad  cursos_previos   promedio
count  20.00000  20.000000       20.000000  20.000000
mean   10.50000  34.100000        3.100000   6.705000
std     5.91608   5.901828        2.531902   1.814409
min     1.00000  27.000000        0.000000   3.700000
25%     5.75000  29.000000        1.000000   5.275000
50%    10.50000  32.500000        2.500000   6.650000
75%    15.25000  40.000000        5.000000   8.225000
max    20.00000  45.000000        8.000000   9.300000

In [ ]:
#esta estructura es para buscar las variables con una caracteristica en común
df[df["promedio"] >= 8.0]
#y esta estructura es para ser mas preciso con dos o mas caractersiticas
df[(df["promedio"] >= 8.0)&(df["activo"] == True)]

    id           nombre  edad        ciudad  cursos_previos  promedio  activo
0    1      Laura Gómez    42      Medellín               0       8.3    True
4    5      María López    29     Manizales               4       8.8    True
7    8   Diego Martínez    33     Cartagena               0       8.2    True
14  15  Lucía Fernández    42  Barranquilla               5       9.0    True

### Limpiar dataSet pero con criterio

Detectar  -> hay algún problema?

In [37]:
df.isnull().sum()

id                0
nombre            0
edad              0
ciudad            0
cursos_previos    0
promedio          0
activo            0
dtype: int64

In [39]:
df = pd.read_csv("estudiantes_ml_2026_.csv")
df.isnull().sum()

nombre                  0
edad                    0
ciudad                  0
pais                    0
genero                  0
nivel_previo            0
horas_estudio_semana    0
promedio                2
modulos_completados     0
activo                  0
fecha_ingreso           0
trabaja_actualmente     0
salario_usd             0
objetivo                0
dtype: int64